### ISSUE TITLE
并发获取zkclient失败

### ISSUE THREAD

**Issue by glameyzhou** [xuxueli/xxl-conf#10]
如果并发获取zkclient实例的时候，出现异常，虽然最前边有加锁的实现，但是没有获取锁的线程会直接报错的。需要细化锁的实现，例如：获取锁、持有锁的时间都需要设置的。

**Comment by xuxueli** [comment]
你好，最新版本 v1.4.0 对重入锁做了优化，增加了二次判断，同时在Spring容器初始化时预热zkclient。从而在业务请求进入系统时，可以直接使用可用的zkclient，避免上述问题。
欢迎升级体验啊！
