### ISSUE TITLE
Spring Boot 如何结合

### ISSUE THREAD

**Issue by 18916204759** [xuxueli/xxl-conf#14]
是否支持Spring Boot？现在项目都是Spring Boot，不通过properties文件，后期有没有结合的方案?

**Comment by xuxueli** [comment]
@MichaelDiane 你好，感谢关注！
最新版本原生支持 springboot ，并且提供了 springboot 版本接入示例项目（“xxl-conf-sample-springboot”），欢迎升级体验哈：）
