### ISSUE TITLE
xxl-conf.properties 加载缺陷

### ISSUE THREAD

**Issue by MichaelDiane** [xuxueli/xxl-conf#15]
目前的加载属性文件，只能讲xxl-conf.properties放到classpath目录下，无法支持讲xxl-conf.properties放到磁盘上；这种方式加载资源文件在发布不同版本时不够灵活。

**Comment by xuxueli** [comment]
@MichaelDiane 你好，喜大普奔！
这个问题在最新版本 v1.4.0 中已经得到修复，原生支持通过属性 “xxl.conf.envprop.location” 自定义配置存放位置，可以存放在resource，也支持存放在磁盘中，欢迎升级体验！
