### ISSUE TITLE
分组名如何指定

### ISSUE THREAD

**Issue by linsage** [xuxueli/xxl-conf#16]
目前注解只能显示固定指定分组名，代码上是否可支持配置文件指定分组名groupName来读取对应的配置。

需求：不同分组对应不同环境

字段类型似乎只支持字符串，希望支持其他基础数据类型

**Comment by xuxueli** [comment]
你好，感谢关注！
注解Key的前缀部分已经包含了分组名，可通过设置多个分组来分别设置各分组配置。
“针对不同分组设置不同环境”，这个需求推荐通过部署多套配置中心来实现啊，避免DB和ZK的相互干扰和耦合。
