### ISSUE TITLE
How to resolve zookeeper miss events?

### ISSUE THREAD

**Issue by PanFreyZheng** [xuxueli/xxl-conf#18]
我最近才开始接触zookeeper,项目上使用过程中因网络问题或多个服务访问同一个节点等原因.监听节点总是会有丢失.导致同步到数据库失败.请问这种情况应该怎么避免或优化呢?谢谢指教.

In the process of development, because of network delay, sometimes there will be no monitoring of znodes, how to avoid or optimize this situation?

**Comment by xuxueli** [comment]
你好，感谢关注啊！
zk原生的Watch是一次性的，在监听到Watch时间时需要重复绑定，可以在Watch逻辑里做处理。
而且，ZK重连之后，也需要重新添加历史Watch。

如果你的需求场景是兼容zk节点，可以考虑接入 XXL-CONF 来实现功能啊？
