### ISSUE TITLE
springcloud启动配置

### ISSUE THREAD

**Issue by eaglewa** [xuxueli/xxl-conf#21]
1、现在是否支持springcloud的配置放入xxlconf，比如数据库配置，hystrix的超时时间，网关的路由等
2、有些公共的配置可能多个项目共享，比如redis的地址，mq的地址等，这个要怎么配置

**Comment by xuxueli** [comment]
你好，上述需求全部支持，而且支持动态变更，推送更新。

提供了三种配置加载方式，"api+注解+xml"，可以经过选择使用。

同时，提供了多和sample项目，包括springboot类型sample项目。

可以参考文档，和sample项目中是使用示例，进行接入使用。

**Comment by xuxueli** [comment]
可前往官网，加群沟通交流。
