### ISSUE TITLE
支持同应用多环境配置吗

### ISSUE THREAD

**Issue by weibo1987** [xuxueli/xxl-conf#22]
看来几遍文档没发现， 是否支持多环境配置呢？

**Comment by xuxueli** [comment]
你好，新版支持多环境配置的。
配置文件中提供了env属性，可根据env属性隔离不同环境配置信息。

**Comment by xuxueli** [comment]
为了避免不同环境相互干扰，配置中心不同环境需要单独部署。

**Comment by xuxueli** [comment]
@weibo1987 你好，最新版本 v1.4.2，原生支持多环境。而且支持自定义环境，欢迎体验。
