### ISSUE TITLE
xxl-conf-admin模块建议

### ISSUE THREAD

**Issue by lixy940** [xuxueli/xxl-conf#24]
建议在xxl-conf-admin模块启动时，增加一个启动类，将mysql中xxl_conf_node表中的数据进行一次初始化，保证数据同步。如：有可能出现，mysql中的数据和zk数据不一致的情况。我在自己测试时就先在mysql存了几条数据，但是当把zk服务启动后，只会去ehcache中取数据进行重新加载到zk。只有在增删改查操作时才对zk和chcache进行更新或缓存。

**Comment by xuxueli** [comment]
你好，感谢反馈！
针对上述情况，稍后会提供 “配置同步检测” 和 “配置同步” 两个功能，方便全量同步配置数据。

**Comment by xuxueli** [comment]
@lixy940 你好，你提到的功能已经实现并推送master分支，将会跟随下个版本：v1.5.0 一起发布。

- 配置同步功能：将会检测对应项目下的全部未同步配置项，使用DB中配置数据覆盖ZK中配置数据并推送更新；在配置中心异常恢复、新配置中心集群初始化等场景中十分有效。
