### ISSUE TITLE
申请加入xxl-conf项目协作开发

### ISSUE THREAD

**Issue by yoqu** [xuxueli/xxl-conf#28]
徐雪里大佬好:
最近公司正在使用xxl-conf项目做配置中心,
对比过现有较流行的阿波罗, diamond,super-diamond.
最终选择了xxl-conf
理由是xxl-conf的轻量级,易扩展且核心功能较为完善等优秀的特性,
非常希望能加入项目一起为xxl-conf贡献一份自己的绵薄之力.希望能够批准

**Comment by xuxueli** [comment]
你好，欢迎欢迎啊 ：）

目前项目以 “Roadmap（TODO） + PR” 的方式迭代开发，可以随时ISSUE提建议，并提交PR。

可以加交流群（ http://www.xuxueli.com/page/community.html ），小窗加好友，随时保持沟通哈。
