### ISSUE TITLE
我们公司现在用的superdiamond,迁移成本有多大?

### ISSUE THREAD

**Issue by kamui0523** [xuxueli/xxl-conf#3]
和superdiamond比的话有什么优势呢?从UI上来看感觉你这个比较友好,但还是向了解下功能上的区别?希望能够抽时间帮忙解答下,多谢~

**Comment by xuxueli** [comment]
你还，特性可以参考下文档的章节1.2：https://my.oschina.net/xuxueli/blog/734267
xxl-conf的接入成本非常低，因为向开发人员开放的API友好度比较高。可以参考example项目尝试下。
如果有问题，可以加入文档中给出的交流QQ群，社区非常活跃。
