### ISSUE TITLE
1.5.0版本xxl-conf-admin中文编辑乱码问题

### ISSUE THREAD

**Issue by czbxyls** [xuxueli/xxl-conf#31]
1.4升级到1.5.0后发现编辑中文配置出现乱码，
经查是application.properties问题：
spring.datasource.url=jdbc:mysql://${mysqladdress:127.0.0.1:3306}/xxl-conf?Unicode=true&amp;amp;characterEncoding=UTF-8

"&amp;amp;" 换成 & 即可。

**Comment by xuxueli** [comment]
赞！

从 1.5.x 版本开始项目已迁移至springboot，配置加载方式有变更，保持与与release版本分支一致即可。
