### ISSUE TITLE
http方式获取数据

### ISSUE THREAD

**Issue by suzhenyu22** [xuxueli/xxl-conf#32]
小组以python工具为主，而且java不会看，请问xxl-conf有没有http方式获取配置呢？

**Comment by xuxueli** [comment]
你好，XXL-CONF针对非Java语言应用，提供 "配置中心Agent服务" 获取配置中心配置。
可以参考文档 （ http://www.xuxueli.com/xxl-conf/ ） 章节 “配置Agent服务（多语言支持）”
