### ISSUE TITLE
客户端能否支持其他缓存?

### ISSUE THREAD

**Issue by jqncc** [xuxueli/xxl-conf#33]
项目已经有缓存组件,不想再引入一个,能否支持常用的redis或者不使用缓存, 存为本地配置文件,因为大部分配置文件频繁修改的情况不多见

**Comment by xuxueli** [comment]
你好，XXL-CONF 底层依赖的Ehcache为单机内存缓存，非常轻量小巧的一个库，并不会对项目带来复杂性。

**Comment by xuxueli** [comment]
如需进一步沟通，可加文档中交流群详细讨论。
