### ISSUE TITLE
是否支持项目公共配置配置一次

### ISSUE THREAD

**Issue by wuxinbo** [xuxueli/xxl-conf#37]
公共配置可能会被多个项目引用，比如mq的配置信息，在这种情况下是否可以将配置抽取成一个公共配置，哪一个项目要用，直接关联改配置即可？当项目有同名配置时，项目的配置覆盖公共配置。

**Comment by xuxueli** [comment]
你好，这种场景 XXL-CONF 是支持的。
XXL-CONF 支持跨项目加载配置数据的，直接加载使用即可。
