### ISSUE TITLE
XXL-CONF客户端不支持灵活配置项目名称appName

### ISSUE THREAD

**Issue by wangtianwen07** [xuxueli/xxl-conf#39]
配置信息在zk上的存储结构为:所有配置信息均会被放置在/xxl-conf节点下，子节点根据环境/项目.KEY生成。如环境为test，项目appName为timer，KEY为spring.datasource.mysql.url的配置信息，在zk上的存储结构为/xxl-conf/test/timer.spring.datasource.mysql.url。

当客户端程序接入配置中心时，需要在@XxlConf注解中指明value=timer.spring.datasource.mysql.url。但是如果项目名称改变，比如由timer编程了timertwo，需要客户端程序修改代码中的value=timertwo.spring.datasource.mysql.url。我希望通过客户端程序在配置文件中配置一个xxl.conf.appName=timertwo. ，value= @XxlConf(value="spring.datasource.mysql.url",defaultValue="")。

本人自己通过修改源码中的XxlConfFactory类，增加private String appName属性，修改postProcessAfterInstantiation方法，将String confKey = xxlConf.value()修改为String confKey = appName + xxlConf.value(); 使用时通过注入@Value("${xxl.conf.appName}")    private String appName;  
      XxlConfFactory xxlConf = new XxlConfFactory();
       xxlConf.setZkaddress(zkaddress);
        xxlConf.setZkdigest(zkdigest);
        xxlConf.setEnv(env);
        xxlConf.setMirrorfile(mirrorfile);
        xxlConf.setAppName(appName);
完成了appName可灵活配置。

但由于不想今后升级到新版本时又需要修改源码，在此提出希望作者加入appName可灵活配置的功能。

**Comment by zhaheng** [comment]
是的，我也遇到这个问题

**Comment by xuxueli** [comment]
感谢反馈，目前项目名仅用于隔离配置信息，单个应用支持加载多个不同项目里的配置信息。
所以，即使项目名变更，配置信息仍然可以正常加载的，二者并没有强关联关系。

上述建议在配置加载时，强制添加项目前缀，这将会破坏改特性。这个还需要再探讨考虑啊。

**Comment by xuxueli** [comment]
感谢反馈，目前项目名仅用于隔离配置信息，单个应用支持加载多个不同项目里的配置信息。
所以，即使项目名变更，配置信息仍然可以正常加载的，二者并没有强关联关系。

上述建议在配置加载时，强制添加项目前缀，这将会破坏改特性。这个还需要再探讨考虑啊。

**Comment by xuxueli** [comment]
感谢反馈，目前项目名仅用于隔离配置信息，单个应用支持加载多个不同项目里的配置信息。
所以，即使项目名变更，配置信息仍然可以正常加载的，二者并没有强关联关系。

上述建议在配置加载时，强制添加项目前缀，这将会破坏改特性。这个还需要再探讨考虑啊。

**Comment by xuxueli** [comment]
感谢反馈，目前项目名仅用于隔离配置信息，单个应用支持加载多个不同项目里的配置信息。
所以，即使项目名变更，配置信息仍然可以正常加载的，二者并没有强关联关系。

上述建议在配置加载时，强制添加项目前缀，这将会破坏改特性。这个还需要再探讨考虑啊。

**Comment by xuxueli** [comment]
感谢反馈，目前项目名仅用于隔离配置信息，单个应用支持加载多个不同项目里的配置信息。
所以，即使项目名变更，配置信息仍然可以正常加载的，二者并没有强关联关系。

上述建议在配置加载时，强制添加项目前缀，这将会破坏改特性。这个还需要再探讨考虑啊。

**Comment by xuxueli** [comment]
感谢反馈，目前项目名仅用于隔离配置信息，单个应用支持加载多个不同项目里的配置信息。
所以，即使项目名变更，配置信息仍然可以正常加载的，二者并没有强关联关系。

上述建议在配置加载时，强制添加项目前缀，这将会破坏改特性。这个还需要再探讨考虑啊。

**Comment by xuxueli** [comment]
感谢反馈，目前项目名仅用于隔离配置信息，单个应用支持加载多个不同项目里的配置信息。
所以，即使项目名变更，配置信息仍然可以正常加载的，二者并没有强关联关系。

上述建议在配置加载时，强制添加项目前缀，这将会破坏改特性。这个还需要再探讨考虑啊。
