### ISSUE TITLE
登陆经常报错

### ISSUE THREAD

**Issue by 843257317** [xuxueli/xxl-conf#4]
每天登陆第一次经常报错，报错信息如下（Could not retrieve transation read-only status server） ，我的mysql是读写的。能正常添加数据，不应该read only ,再次刷新可以正常进入conf页面

org.springframework.dao.TransientDataAccessResourceException: 
### Cause: java.sql.SQLException: Could not retrieve transation read-only status server

; SQL []; Could not retrieve transation read-only status server; nested exception is java.sql.SQLException: Could not retrieve transation read-only status server

**Comment by xuxueli** [comment]
该情况无法复现，请检查或更换mysql实例；

**Comment by 843257317** [comment]
分别在测试和生产两个环境上部署了xxl-conf，用的不同的mysql实例，均有以上现象。同一个mysql服务器上除了xxl的数据库以外还有其他业务库。业务库均没有出现问题。应该可以排除mysql的问题。而且上面那个出现后，只要刷新页面便可正常访问xxl-conf

**Comment by 843257317** [comment]
我查了下报错。可能是mysql驱动包 版本过低导致

http://bbs.csdn.net/topics/390429553

**Comment by xuxueli** [comment]
谢谢关注！
master分支pom文件中的的mysql驱动，对应的是mysql5.6版本；如果mysql版本不匹配，可以自己定制。
后面会做驱动版本升级；

**Comment by 843257317** [comment]
我们mysql的版本是5.6.29。只是不确定是不是驱动问题。我们先试试吧。

**Comment by 843257317** [comment]
升级了mysql驱动问题依然存在。怀疑是事物隔离级别导致的问题。我们用的mysql的事物隔离级别是repeatable read

**Comment by xuxueli** [comment]
我刚对比了本地的mysql版本和事务隔离级别，和你们基本一致，但是却没有重现这个问题。
你们别的业务系统存在这个问题吗？可以对比下现有业务系统的DB连接池配置，然后定位一下问题。

**Comment by 843257317** [comment]
我们最近修改了代码解决了这个问题，在连接池配置里加了一个参数numTestsPerEvictionRun问题得到解决

**Comment by xuxueli** [comment]
你们更换了默认的c3p0连接池吗？用的DBCP？

**Comment by 843257317** [comment]
是的org.apache.commons.dbcp.BasicDataSource

**Comment by xdxiaodong** [comment]
不是别人更换了默认的c3p0连接池用的DBCP，而是现在github里面的代码就是用的DBCP，我也遇到了同样的问题

**Comment by xuxin0612** [comment]
请问这个问题有比较好的解释吗，或者一些链接

**Comment by xuxueli** [comment]
@843257317 @xuxin0612 这个问题原因是MySQL会主动断开8H无请求的连接，但是连接池没有主动释放无效连接导致的。
新版本针对这种问题已经住了处理和优化，线上运行稳定，可以参考调整下连接池配置啊。

**Comment by xuxueli** [comment]
大家好，最新版本 v1.4.0 已经正式发布，新增诸多实用特性，如：配置权限、用户管理、springboot支持、注解获取配置（注解+XML+API，且均支持动态推送更新）、配置变更listener……等等。

@843257317 欢迎升级体验啊
