### ISSUE TITLE
建议追加LDAP功能

### ISSUE THREAD

**Issue by PostgreSQL1989** [xuxueli/xxl-conf#46]
一般来说，用户管理是公司内部使用的。
建议可以接入LDAP或SSO，以便和公司内部的账号认证打通。

**Comment by xuxueli** [comment]
你好，各公司SSO实现不同，没办法做统一。如需接入SSO可以自行定制。

**Comment by PostgreSQL1989** [comment]
> 你好，各公司SSO实现不同，没办法做统一。如需接入SSO可以自行定制。

感谢你的回复。
那不知道是否可以考虑支持LDAP？
