### ISSUE TITLE
这个不就是一个zk client吗？  

### ISSUE THREAD

**Issue by Simonfld** [xuxueli/xxl-conf#5]
有什么优势？

**Comment by xuxueli** [comment]
您好，XXL-CONF 是一个分布式配置管理平台，其核心设计目标是“为分布式业务提供统一的配置管理服务”。
托管在系统中的 “配置信息” 支持在线更新，实时推送至业务逻辑（一段Java代码）中。ZK在系统中只是起到了配置更新时的广播功能，其次系统针对配置做了Local Cache以及必要的备份。
感谢关注 ：）
