### ISSUE TITLE
更新到1.5.0 zkBasePath问题

### ISSUE THREAD

**Issue by xssxyby** [xuxueli/xxl-conf#54]
你好，初步接触这个，我发现1.5.0版本之后`XxlConfZkConf`中的`zkBasePath`是`static final的`了，值固定为`/xxl-conf`，之前版本可以自己配置，请问是出于什么考虑的，如果我们的项目从1.4.0升级到1.5.0，节点路径这块应该会有问题吧，需要怎么处理呢

**Comment by xuxueli** [comment]
你好，新版只固定了配置前缀为 “/xxl-conf”，但是环境路径依然可以自定义的啊。完整配置路径为 “前缀 + 环境 + 配置Key” 三部分组成。

新版本在配置迁移、升级方便非常方便，只需要两步：
- 1、copy 配置数据至配置表；
- 2、配置界面点击 "全量同步" 。

详情可参考文档章节 “5.6 配置同步功能”

**Comment by liuxianfa520** [comment]
您好，目前我们项目使用的1.4.0版本的xxl-conf-core，应该不能平滑升级到1.5.x版本吧？

            <dependency>
                <groupId>com.xuxueli</groupId>
                <artifactId>xxl-conf-core</artifactId>
                <version>1.4.0</version>
            </dependency>


因为项目已经上线，并且调用方还是比较多的，无法让所有用到xxl-conf-core的部门同时发版。
所以，我也有同样的疑问。
