### ISSUE TITLE
管理平台修改配置偶尔会不生效

### ISSUE THREAD

**Issue by zhangshichen0** [xuxueli/xxl-conf#55]
![image](https://user-images.githubusercontent.com/38861893/47905679-a5b62700-dec2-11e8-9b9c-16c424c893a5.png)

在管理平台修改配置时，有可能获取到的是代理对象，然后造成配置修改不生效

**Comment by xuxueli** [comment]
你好，可以提供问题复现的代码以及操作步骤吗？

存在代理的情况下，推荐采用API方式获取配置，更加稳定，APi方式底层存在Local Cache不必担心性能问题。
