### ISSUE TITLE
项目不能启动的原因

### ISSUE THREAD

**Issue by liuyanjun3366** [xuxueli/xxl-conf#6]
按github上面下载下来部署，启动不了，是那个硬盘绝对路径配置的问题吗

**Comment by 843257317** [comment]
在指定的路径下面配好zk地址试试

**Comment by liuyanjun3366** [comment]
嗯，是这样配了，也在根目录下加了文件，但是会启动超时，也没具体错误

**Comment by liuyanjun3366** [comment]
建议写个部署文档之类的，这样部署起来就方便了，可能是哪个地方疏忽了

**Comment by xuxueli** [comment]
大家好，最新版本 v1.4.0 已经发布，新增了诸多特性功能，如 “配置权限、用户管理、springboot支持、注解获取配置、配置变更listener……” 等等。

项目文档已经经过重新梳理，快速入门章节与操作指南也做了优化，欢迎下载体验哈！
