### ISSUE TITLE
值的获取

### ISSUE THREAD

**Issue by dsl1888888** [xuxueli/xxl-conf#64]
properties上
test.conf=#{T(com.xxl.conf.core.XxlConfClient).get('default.key02')}

这样获取的值，没法 实时  更新的？

**Comment by xuxueli** [comment]
你好，这种方式的配置没办法关联到具体的Bean。可以参考文档中提到的几种方式，选择支持刷新Bean的方式使用，比如：注解方式、XML方式等等；
