### ISSUE TITLE
refreshCacheAndMirror中的镜像文件更新

### ISSUE THREAD

**Issue by ciphermagic** [xuxueli/xxl-conf#65]
你好，`XxlConfLocalCacheConf#refreshCacheAndMirror`中，每次都全量把localCache的值更新到Mirror中，不会影响性能吗？为什么不判断value有变更才更新呢？

**Comment by xuxueli** [comment]
你好，每次同步只是写一次磁盘文档，对性能影响有限，可以忽略的。
