### ISSUE TITLE
客户端的磁盘快照如何使用

### ISSUE THREAD

**Issue by ciphermagic** [xuxueli/xxl-conf#66]
客户端的磁盘快照只是在初始化时用到（`ConfLocalCacheConf#init`），那么在远程配置中心故障时如何降级使用镜像文件呢？是要重启客户端吗?
>>> http://www.xuxueli.com/xxl-conf/#/?id=_58-容灾性

**Comment by xuxueli** [comment]
你好，远程配置中心故障时会自动降级使用镜像配置，不需要做任何操作。
- 运行时配置中心故障：将会使用LocalCache中配置数据，该数据会自动同步至镜像文件；
- 启动时配置中心故障：XxlConfLocalCacheConf.init() 会从镜像文件初始化LocalCache，供业务方使用；
