### ISSUE TITLE
一直报request fail, msg=Monitor timeout

### ISSUE THREAD

**Issue by mojie126** [xuxueli/xxl-conf#69]
最新的1.6.1版本

**Comment by ciphermagic** [comment]
这个是正常的，客户端与服务端建立30s长连接，服务端没有配置更新时，就会返回`Monitor timeout.`

**Comment by mojie126** [comment]
昂...那能不能换个提示...我调了一下午，都没找到原因...

**Comment by ciphermagic** [comment]
> 昂...那能不能换个提示...我调了一下午，都没找到原因...

参考这里： https://github.com/xuxueli/xxl-conf/blob/master/xxl-conf-admin/src/main/java/com/xxl/conf/admin/service/impl/XxlConfNodeServiceImpl.java#L380

**Comment by mojie126** [comment]
好的，谢谢...
另外我发现用注解无法获取变更...不知道是不是我使用的问题...

**Comment by ciphermagic** [comment]
如果用API方式可以获取，用注解不可以，看看是不是配置项所属对象被代理了

- [57-对象代理情况下配置获取](http://www.xuxueli.com/xxl-conf/#/?id=_57-对象代理情况下配置获取)

**Comment by xuxueli** [comment]
@mojie126 你好，兼容超时的日志 ”Monitor timeout“ 已经调整为debug级别。进一步降低log数据量，非核心log统一调整为debug级别。
