### ISSUE TITLE
bug: 存在"不一致性读"的问题

### ISSUE THREAD

**Issue by beCat** [xuxueli/xxl-conf#72]
@XxlConf("default.key02")
    public String paramByAnno;

    @RequestMapping("/test")
    @ResponseBody
    public String index() {
        // 这里存在一个问题：在下列代码执行的时候，如果在20s内配置中心更新了该key对应的值，那么就会出现“非一致性读”的问题。
        logger.info("1----------->{}", paramByAnno);  // 打印出值 123
        try {
        // 配置中心更新了该key对应的值456
            Thread.sleep(20000L);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        logger.info("2--------->{}", paramByAnno);  // 打印出新值 456
        return paramByAnno;
    }

**Comment by bkblack** [comment]
这个问题框架很难解决，最好定义局部变量
