### ISSUE TITLE
配置文件有误，已定位问题，作者进来看下更新下

### ISSUE THREAD

**Issue by xdxiaodong** [xuxueli/xxl-conf#8]
xxl-conf\xxl-conf-admin\src\main\resources\springapplicationcontext-database.xml

错误的：
<bean id="propertyConfigurer" class="org.springframework.beans.factory.config.PropertyPlaceholderConfigurer">
		<property name="fileEncoding" value="utf-8" />
		<property name="ignoreResourceNotFound" value="true" />
		<property name="order" value="1"/>
		<property name="ignoreUnresolvablePlaceholders" value="true" />
		<property name="locations">
			<list>
				<value>classpath*:xxl-config.properties</value>
			</list>
		</property>
	</bean>
正确的：
<bean id="propertyConfigurer" class="org.springframework.beans.factory.config.PropertyPlaceholderConfigurer">
		<property name="fileEncoding" value="utf-8" />
		<property name="ignoreResourceNotFound" value="true" />
		<property name="order" value="1"/>
		<property name="ignoreUnresolvablePlaceholders" value="true" />
		<property name="locations">
			<list>
				<value>classpath*:xxl-conf.properties</value>
			</list>
		</property>
	</bean>

原因：
配置文件名字是 xxl-conf\xxl-conf-admin\src\main\resources\xxl-conf.properties

**Comment by xuxueli** [comment]
你好，感谢关注！
这是配置文件统一迁移时遗留的问题，相关调整已经推送master分支，可以pull最新代码或者下载最新release包回归测试，再次感谢问题反馈！
