### ISSUE TITLE
针对一次性加载配置，值更新问题

### ISSUE THREAD

**Issue by shang7053** [xuxueli/xxl-conf#9]
看到文档说类似数据库连接，第一次加载后，值发生变化，不能自动更新。是否可以考虑使用context的refresh，刷新配置？
XmlWebApplicationContext context =
                                 (XmlWebApplicationContext)WebApplicationContextUtils
                                 .getWebApplicationContext(request.getServletContext());
                 context.refresh();

**Comment by xuxueli** [comment]
你好，感谢关注和建议！
新版本 v1.4.0 针对“注解、XML、API”三种获取配置方式，均支持配置动态刷新。
同时提供了配置监听功能，在此技术上支持实现类似JDBC配置变更后，重新创建数据库连接的功能。
